### ISSUE TITLE
`govm remove --all` does not work

### ISSUE THREAD

**Issue by marcemq** [govm-project/govm#16]
From `help` command:
```
$ govm remove --help
NAME:
   govm remove - Remove vms

USAGE:
   govm remove [command options] [arguments...]

OPTIONS:
   --all              Remove all vms
   --namespace value  list VMs from this namespace (default: "<username>")
```

It is stated that we can remove all current `vms`, but it does not work.
```
$ govm remove --all
missing VM name
USAGE:
 govm remove [command options] [name]
```

The current workaround is to remove the current `vms` one by one.

**Comment by obedmr** [comment]
Fixed with https://github.com/govm-project/govm/commit/3d8c080b0d6d31b1874eb822d9940ae9380d58a3
